#!/usr/bin/env ruby

require 'nest_connect'
require 'thor'

module NestConnect
  class App < Thor
    desc 'authorize', 'Get an access token'
    method_option :auth_code, desc: 'Pincode to connect with Nest', required: true
    method_option :client_id, desc: 'Client ID', required: true
    method_option :client_secret, desc: 'Client Secret', required: true

    def authorize
      NestConnect::API::Authorize.new(
        auth_code: options[:auth_code],
        client_id: options[:client_id],
        client_secret: options[:client_secret]
      ).run
    end

    desc 'stream', 'Debug Nest API streaming'
    def stream
      NestConnect::API::Stream.new.run
    end
  end
end

NestConnect::App.start
